References :
* https://www.youtube.com/watch?v=PFDu9oVAE-g
* https://www.youtube.com/watch?v=EJG6gBeVdfw
* https://intuitive-math.club/linear-algebra/eigenbasis/

Based on homework for week 5 of course : https://www.coursera.org/learn/linear-algebra-machine-learning

In [2]:
import numpy as np

In this quiz you will diagonalise some matrices and apply this to simplify calculations

## 1. 

Given the matrix $T=
\begin{pmatrix}6&−1\\2 & 3\end{pmatrix}$ and change of basis matrix $C=\begin{pmatrix}1 & 1\\1 & 2 \end{pmatrix}$ (whose columns are eigenvectors of $T$), calculate the diagonal matrix $D = C^{-1}TC$

In [3]:
T = np.matrix([[6,-1],
               [2,3]])

C_eigbasis = np.matrix(([1,1],
                        [1,2]))

C_eigbasis_inv = np.linalg.inv(C_eigbasis)

D = np.matmul(   C_eigbasis_inv, np.matmul(T,C_eigbasis))

D

matrix([[5., 0.],
        [0., 4.]])

## 2. 
Given the matrix $T=
\begin{pmatrix}2 & 7 \\ 0 & -1  \end{pmatrix}$
 and change of basis matrix $C = \begin{pmatrix}7 & 1\\ -3 & 0   \end{pmatrix}    $ (whose columns are eigenvectors of $T$), calculate the diagonal matrix $D = C^{-1}TC$.

In [4]:
T = np.matrix([[2,7],
               [0,-1]])
C_eigbasis = np.matrix([[7,1],
                        [-3,0]])
C_eigbasis_inv = np.linalg.inv(C_eigbasis)
D = np.matmul(C_eigbasis_inv, np.matmul(T,C_eigbasis))

D

matrix([[-1.,  0.],
        [ 0.,  2.]])

## 3.
Given the matrix $T=
\begin{pmatrix}1 & 0 \\ 2 & -1  \end{pmatrix}$
 and change of basis matrix $C = \begin{pmatrix}1 & 0\\ 1 & 1   \end{pmatrix}    $ (whose columns are eigenvectors of $T$), calculate the diagonal matrix $D = C^{-1}TC$.

In [5]:
T = np.matrix([[1,0],
               [2,-1]])
C_eigbasis = np.matrix([[1,0],
                        [1,1]])

C_eigbasis_inv = np.linalg.inv(C_eigbasis)

D = np.matmul(C_eigbasis_inv,np.matmul(T,C_eigbasis))
D

matrix([[ 1.,  0.],
        [ 0., -1.]])

## 4. 
Given that $T= \begin{pmatrix}
6 & -1\\
2 & 3
\end{pmatrix}
= 
\begin{pmatrix}
1 &  1\\
1 &  2
\end{pmatrix}
\begin{pmatrix}
5 &  0\\
0 &  4
\end{pmatrix}
\begin{pmatrix}
2 &  -1\\
-1 &  1
\end{pmatrix}
$, calculate $T^3$ 

 .

In [6]:
D = np.diag([5,4])
C_eigbasis = np.matrix([[1,1],
                        [1,2]])
C_eigbasis_inv = np.linalg.inv(C_eigbasis)

T_cube =  np.matmul(    C_eigbasis,
             np.matmul( np.power(D,3),
                        C_eigbasis_inv
                      )       
                   )

T_cube

matrix([[186., -61.],
        [122.,   3.]])

## 5. 
Given that $T= \begin{pmatrix}
2 & 7\\
0 & -1
\end{pmatrix}
= 
\begin{pmatrix}
7 &  1\\
-3 &  0
\end{pmatrix}
\begin{pmatrix}
-1 &  0\\
0 &  2
\end{pmatrix}
\begin{pmatrix}
0 &  -1/3\\
1 &  7/3
\end{pmatrix}
$, calculate $T^3$ 

 .
 

In [7]:
D = np.diag([-1,2])
C_eigbasis = np.matrix([[7,1],
                        [-3,0]])

C_eigbasis_inv = np.linalg.inv(C_eigbasis)

T_cube = np.matmul(C_eigbasis ,
         np.matmul(np.power(D,3)    ,
                   C_eigbasis_inv          ))

T_cube

matrix([[ 8., 21.],
        [ 0., -1.]])

## 6. 
Given that $T= \begin{pmatrix}
1 & 0\\
2 & -1
\end{pmatrix}
= 
\begin{pmatrix}
1 &  0\\
1 &  1
\end{pmatrix}
\begin{pmatrix}
1 &  0\\
0 &  -1
\end{pmatrix}
\begin{pmatrix}
1 &  0\\
-1 &  1
\end{pmatrix}
$, calculate $T^3$ 

 .
 

In [8]:
D = np.diag([1,-1])
C_eigbasis = np.matrix([[1,0],
                        [1,1]])
C_eigbasis_inv = np.linalg.inv(C_eigbasis)

T_pow_5 = np.matmul(      C_eigbasis,
              np.matmul(  np.power(D,5) ,
                          C_eigbasis_inv))

T_pow_5

matrix([[ 1.,  0.],
        [ 2., -1.]])

## Extra
Create a general function that receives a matrix and a power (scalar) and returns the matrix powered to the given power using diagonalization through eigenbasis descomposition:

In [9]:
def matrix_power(matrix,power=2):
    assert matrix.shape[0] == matrix.shape[1]
    
    matrix_dimension = matrix.shape[0]
    eig_values,eig_vectors = np.linalg.eig(matrix)
    
    # if the matrix has more eigenvectors than it's dimension, use only the first n as basis
    eig_values = eig_values[:matrix_dimension]
    eig_basis = eig_vectors[:,:matrix_dimension]
    
    eig_basis_inv = np.linalg.inv(eig_basis)
    
    #create diagonal matrix of eigenvalues
    diagonal_matrix = np.diag(eig_values)
    
    diagonal_matrix_powered = np.power(diagonal_matrix,power)
    
    powered_matrix = np.matmul(  eig_basis,
                       np.matmul( diagonal_matrix_powered ,   
                                  eig_basis_inv
                                )         
                                
                                )
    
    return powered_matrix
    
matrix_power(T,2)

matrix([[1., 0.],
        [0., 1.]])

Given that $T= \begin{pmatrix}
6 & -1\\
2 & 3 
\end{pmatrix}$  calculate $T^3$ .

In [10]:
T = np.matrix([[6,-1],
              [2,3]])

matrix_power(T,3)

matrix([[186., -61.],
        [122.,   3.]])

## Final quiz

### 1. 
To practice, select all eigenvectors of the matrix $A = \begin{bmatrix}4 & -5 & 6 \\ 7 & -8 & 6 \\ 3/2 & -1/2 & -2\end{bmatrix}$

In [25]:
A = np.matrix([[4 , -5 , 6] , 
              [7 , -8 , 6] ,
              [3/2 , -1/2 , -2]] )

In [26]:
eig_val, eig_vec = np.linalg.eig(A)

In [27]:
eig_val

array([ 1., -4., -3.])

In [28]:
eig_vec

matrix([[-0.6882472 , -0.66666667,  0.40824829],
        [-0.6882472 , -0.66666667, -0.40824829],
        [-0.22941573,  0.33333333, -0.81649658]])

### 2. 

Recall from the PageRank notebook, that in PageRank, we care about the eigenvector of the link matrix, $L$, that has eigenvalue 1, and that we can find this using power iteration method as this will be the largest eigenvalue.

PageRank can sometimes get into trouble if closed-loop structures appear. A simplified example might look like this,

<img src="https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/95T5jO8QEeeFrgryCjqNWg_a7ac8d21dc15703802fb2166e3326101_loop.png?expiry=1585699200000&hmac=qqFNqoGyOuUp4LkixJjFQhsQ6H-3Py1W3vG9YfztLMw">

With link matrix, $L = \begin{bmatrix} 0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \end{bmatrix}$

Calculate the eigenvalues and vectors for this system.

What might be going wrong? Select all that apply.

In [35]:
L = np.eye(4,4,-1)
L[0,-1] = 1
print(L)

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [38]:
eig_val ,eig_vec = np.linalg.eig(L)

print("Eigen values:")
print(eig_val)

Eigen values:
[-1.00000000e+00+0.j  8.32667268e-17+1.j  8.32667268e-17-1.j
  1.00000000e+00+0.j]


In [40]:
print("Eigen vectors:")
print(np.round(eig_vec,3))

Eigen vectors:
[[-0.5+0.j   0. -0.5j  0. +0.5j -0.5+0.j ]
 [ 0.5+0.j  -0.5+0.j  -0.5-0.j  -0.5+0.j ]
 [-0.5+0.j  -0. +0.5j -0. -0.5j -0.5+0.j ]
 [ 0.5+0.j   0.5+0.j   0.5-0.j  -0.5+0.j ]]


What might be going wrong? Select all that apply.


* Other eigenvalues are not small compared to 1, and so do not decay away with each power iteration.

    Correct
    The other eigenvectors have the same size as 1 (they are -1, ii, -i−i)


* The system is too small.


* Some of the eigenvectors are complex.

    This should not be selected
    This isn't actually a problem, so long as the eigenvector with value 1 is purely real.


* Because of the loop, Procrastinating Pats that are browsing will go around in a cycle rather than settling on a webpage.

    Correct
    If all sites started out populated equally, then the incoming pats would equal the outgoing, but in general the system will not converge to this result by applying power iteration.


* None of the other options.


### 3. 
The loop in the previous question is a situation that can be remedied by damping.

If we replace the link matrix with the damped, $L' = \begin{bmatrix} 0.1 & 0.1 & 0.1 & 0.7 \\ 0.7
 & 0.1 & 0.1 & 0.1 \\ 0.1 & 0.7 & 0.1 & 0.1 \\ 0.1 & 0.1 & 0.7 & 0.1 \end{bmatrix}$, how does this help?

In [44]:
L_prime = np.matrix( [[0.1 , 0.1 , 0.1 , 0.7 ],
[ 0.7, 0.1 , 0.1 , 0.1 ] ,
[0.1 , 0.7 , 0.1 , 0.1 ] ,
[0.1 , 0.1 , 0.7 , 0.1 ]])

eig_val ,eig_vec = np.linalg.eig(L_prime)

print("Eigen values:")
print(eig_val)

Eigen values:
[ 1.0000000e+00+0.j  -6.0000000e-01+0.j  -1.2490009e-16+0.6j
 -1.2490009e-16-0.6j]


In [45]:
print("Eigen vectors:")
print(np.round(eig_vec,3))

Eigen vectors:
[[ 0.5+0.j   0.5+0.j   0.5+0.j   0.5-0.j ]
 [ 0.5+0.j  -0.5+0.j   0. -0.5j  0. +0.5j]
 [ 0.5+0.j   0.5+0.j  -0.5+0.j  -0.5-0.j ]
 [ 0.5+0.j  -0.5+0.j  -0. +0.5j -0. -0.5j]]





* The other eigenvalues get smaller.

    Correct
    So their eigenvectors will decay away on power iteration.


* The complex number disappear.


* None of the other options.


* There is now a probability to move to any website.

    Correct
    This helps the power iteration settle down as it will spread out the distribution of Pats


* It makes the eigenvalue we want bigger.




### 4.  

Given the matrix $A = \begin{bmatrix} 3/2 & -1 \\ -1/2 & 1/2 \end{bmatrix}$, calculate its characteristic polynomial.


$\lambda^2 - 2\lambda + \frac{1}{4}λ$ 

In [13]:
A = np.matrix([[3/2 , -1],
               [-1/2,1/2]])

eig_val , eig_vec = np.linalg.eig(A)

By solving the characteristic polynomial above or otherwise, calculate the eigenvalues of the matrix  

In [14]:
eig_val

array([1.8660254, 0.1339746])

In [24]:
eig_vec

matrix([[ 0.9390708 ,  0.59069049],
        [-0.34372377,  0.80689822]])

In [18]:
eig_basis = eig_vec
eig_basis_inv = np.linalg.inv(eig_basis)

Form the matrix $C$ whose left column is the vector $v_{1}$ and whose right column is $v_{2}$ from immediately above.

By calculating $D = C^{-1}AC$ or by using another method, find the diagonal matrix $D$.

In [22]:
D = np.round (np.matmul(eig_basis_inv,np.matmul(A,eig_basis)) ,3 )

D

array([[1.866, 0.   ],
       [0.   , 0.134]])

By using the diagonalisation above or otherwise, calculate $A^2$
 .

In [23]:
matrix_power(A,2)

matrix([[ 2.75, -2.  ],
        [-1.  ,  0.75]])