References :
* https://www.youtube.com/watch?v=PFDu9oVAE-g
* https://www.youtube.com/watch?v=EJG6gBeVdfw
* https://intuitive-math.club/linear-algebra/eigenbasis/

Based on homework for week 5 of course : https://www.coursera.org/learn/linear-algebra-machine-learning

In [1]:
import numpy as np

In this quiz you will diagonalise some matrices and apply this to simplify calculations

## 1. 

Given the matrix $T=
\begin{pmatrix}6&−1\\2 & 3\end{pmatrix}$ and change of basis matrix $C=\begin{pmatrix}1 & 1\\1 & 2 \end{pmatrix}$ (whose columns are eigenvectors of $T$), calculate the diagonal matrix $D = C^{-1}TC$

In [10]:
T = np.matrix([[6,-1],
               [2,3]])

C_eigbasis = np.matrix(([1,1],
                        [1,2]))

C_eigbasis_inv = np.linalg.inv(C_eigbasis)

D = np.matmul(   C_eigbasis_inv, np.matmul(T,C_eigbasis))

D

matrix([[5., 0.],
        [0., 4.]])

## 2. 
Given the matrix $T=
\begin{pmatrix}2 & 7 \\ 0 & -1  \end{pmatrix}$
 and change of basis matrix $C = \begin{pmatrix}7 & 1\\ -3 & 0   \end{pmatrix}    $ (whose columns are eigenvectors of $T$), calculate the diagonal matrix $D = C^{-1}TC$.

In [12]:
T = np.matrix([[2,7],
               [0,-1]])
C_eigbasis = np.matrix([[7,1],
                        [-3,0]])
C_eigbasis_inv = np.linalg.inv(C_eigbasis)
D = np.matmul(C_eigbasis_inv, np.matmul(T,C_eigbasis))

D

matrix([[-1.,  0.],
        [ 0.,  2.]])

## 3.
Given the matrix $T=
\begin{pmatrix}1 & 0 \\ 2 & -1  \end{pmatrix}$
 and change of basis matrix $C = \begin{pmatrix}1 & 0\\ 1 & 1   \end{pmatrix}    $ (whose columns are eigenvectors of $T$), calculate the diagonal matrix $D = C^{-1}TC$.

In [18]:
T = np.matrix([[1,0],
               [2,-1]])
C_eigbasis = np.matrix([[1,0],
                        [1,1]])

C_eigbasis_inv = np.linalg.inv(C_eigbasis)

D = np.matmul(C_eigbasis_inv,np.matmul(T,C_eigbasis))
D

matrix([[ 1.,  0.],
        [ 0., -1.]])

## 4. 
Given that $T= \begin{pmatrix}
6 & -1\\
2 & 3
\end{pmatrix}
= 
\begin{pmatrix}
1 &  1\\
1 &  2
\end{pmatrix}
\begin{pmatrix}
5 &  0\\
0 &  4
\end{pmatrix}
\begin{pmatrix}
2 &  -1\\
-1 &  1
\end{pmatrix}
$, calculate $T^3$ 

 .

In [24]:
D = np.diag([5,4])
C_eigbasis = np.matrix([[1,1],
                        [1,2]])
C_eigbasis_inv = np.linalg.inv(C_eigbasis)

T_cube =  np.matmul(    C_eigbasis,
             np.matmul( np.power(D,3),
                        C_eigbasis_inv
                      )       
                   )

T_cube

matrix([[186., -61.],
        [122.,   3.]])

## 5. 
Given that $T= \begin{pmatrix}
2 & 7\\
0 & -1
\end{pmatrix}
= 
\begin{pmatrix}
7 &  1\\
-3 &  0
\end{pmatrix}
\begin{pmatrix}
-1 &  0\\
0 &  2
\end{pmatrix}
\begin{pmatrix}
0 &  -1/3\\
1 &  7/3
\end{pmatrix}
$, calculate $T^3$ 

 .
 

In [27]:
D = np.diag([-1,2])
C_eigbasis = np.matrix([[7,1],
                        [-3,0]])

C_eigbasis_inv = np.linalg.inv(C_eigbasis)

T_cube = np.matmul(C_eigbasis ,
         np.matmul(np.power(D,3)    ,
                   C_eigbasis_inv          ))

T_cube

matrix([[ 8., 21.],
        [ 0., -1.]])

## 6. 
Given that $T= \begin{pmatrix}
1 & 0\\
2 & -1
\end{pmatrix}
= 
\begin{pmatrix}
1 &  0\\
1 &  1
\end{pmatrix}
\begin{pmatrix}
1 &  0\\
0 &  -1
\end{pmatrix}
\begin{pmatrix}
1 &  0\\
-1 &  1
\end{pmatrix}
$, calculate $T^3$ 

 .
 

In [29]:
D = np.diag([1,-1])
C_eigbasis = np.matrix([[1,0],
                        [1,1]])
C_eigbasis_inv = np.linalg.inv(C_eigbasis)

T_pow_5 = np.matmul(      C_eigbasis,
              np.matmul(  np.power(D,5) ,
                          C_eigbasis_inv))

T_pow_5

matrix([[ 1.,  0.],
        [ 2., -1.]])

## Extra
Create a general function that receives a matrix and a power (scalar) and returns the matrix powered to the given power using diagonalization through eigenbasis descomposition:

In [52]:
def matrix_power(matrix,power=2):
    assert matrix.shape[0] == matrix.shape[1]
    
    matrix_dimension = matrix.shape[0]
    eig_values,eig_vectors = np.linalg.eig(matrix)
    
    # if the matrix has more eigenvectors than it's dimension, use only the first n as basis
    eig_values = eig_values[:matrix_dimension]
    eig_basis = eig_vectors[:,:matrix_dimension]
    
    eig_basis_inv = np.linalg.inv(eig_basis)
    
    #create diagonal matrix of eigenvalues
    diagonal_matrix = np.diag(eig_values)
    
    diagonal_matrix_powered = np.power(diagonal_matrix,power)
    
    powered_matrix = np.matmul(  eig_basis,
                       np.matmul( diagonal_matrix_powered ,   
                                  eig_basis_inv
                                )         
                                
                                )
    
    return powered_matrix
    
matrix_power(T,2)

matrix([[34., -9.],
        [18.,  7.]])

Given that $T= \begin{pmatrix}
6 & -1\\
2 & 3 
\end{pmatrix}$  calculate $T^3$ .

In [53]:
T = np.matrix([[6,-1],
              [2,3]])

matrix_power(T,3)

matrix([[186., -61.],
        [122.,   3.]])