<a href="https://colab.research.google.com/github/llealgt/linear_algebra/blob/master/Project_3D_data_onto_a_2D_subspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project 3D data onto a 2D subspace

In [1]:
import numpy as np

1. 
For a vector \mathbf{x} =
⎡⎣600⎤⎦
x= 
⎣
⎢
⎡
​	
  
6
0
0
​	
  
⎦
⎥
⎤
​	
  and the subspace UU spanned by the basis vectors \mathbf{b}_1=
⎡⎣111⎤⎦
b 
1
​	
 = 
⎣
⎢
⎡
​	
  
1
1
1
​	
  
⎦
⎥
⎤
​	
  and \mathbf{b}_2=
⎡⎣012⎤⎦
b 
2
​	
 = 
⎣
⎢
⎡
​	
  
0
1
2
​	
  
⎦
⎥
⎤
​	
 , which of the following statements are true?

In [22]:
b1 = np.array([[1,1,1]])
b2 = np.array([[0,1,2]])
B = np.concatenate((b1,b2),axis=0).T
x = np.array([6,0,0])

coord_matrix = np.matmul(np.linalg.inv(np.matmul(B.T,B)),B.T)
B_coord = np.matmul(coord_matrix,x)
proyection_matrix = np.matmul(B,coord_matrix)

print("proy(x) in U basis coordinates: ",B_coord)
print("proy(x) in original basis coordinates: ",np.matmul(B,B_coord))
print("proyection matrix :")
print(proyection_matrix)


proy(x) in U basis coordinates:  [ 5. -3.]
proy(x) in original basis coordinates:  [ 5.  2. -1.]
proyection matrix :
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


Project 
⎡⎣322⎤⎦
⎣
⎢
⎡
​	
  
3
2
2
​	
  
⎦
⎥
⎤
​	
  onto the subspace spanned by 
⎡⎣100⎤⎦
⎣
⎢
⎡
​	
  
1
0
0
​	
  
⎦
⎥
⎤
​	
  and 
⎡⎣011⎤⎦
⎣
⎢
⎡
​	
  
0
1
1
​	
  
⎦
⎥
⎤
​	
 .

In [31]:
x = np.array([[3,2,2]]).T

b1 = np.array([[1,0,0]]).T
b2 = np.array([[0,1,1]]).T

B = np.concatenate((b1,b2),axis = 1)

coord_matrix = np.matmul(np.linalg.inv(np.matmul(B.T,B)),B.T)
proyection_matrix = np.matmul(B,coord_matrix)
proyection_x = np.matmul(proyection_matrix,x)

print("Proyection of x:")
print(proyection_x)


Proyection of x:
[[3.]
 [2.]
 [2.]]


2 

Project 
⎡⎣1200⎤⎦
⎣
⎢
⎡
​	
  
12
0
0
​	
  
⎦
⎥
⎤
​	
  onto the subspace U_1U 
1
​	
  spanned by 
⎡⎣111⎤⎦
,
⎡⎣012⎤⎦
⎣
⎢
⎡
​	
  
1
1
1
​	
  
⎦
⎥
⎤
​	
 , 
⎣
⎢
⎡
​	
  
0
1
2
​	
  
⎦
⎥
⎤
​	
 .
Project the result from 1. onto the subspace spanned by 
⎡⎣⎢−106√−46√26√⎤⎦⎥
⎣
⎢
⎡
​	
  
−10 
6
​	
 
−4 
6
​	
 
2 
6
​	
 
​	
  
⎦
⎥
⎤
​	
 . What is the final projection?
Hint: For step 2. you do not necessarily need to compute anything.

In [33]:
x = np.array([[12,0,0]]).T

b1 = np.array([[1,1,1]]).T
b2 = np.array([[0,1,2]]).T
B = np.concatenate((b1,b2),axis=1)

coord_matrix = np.matmul(np.linalg.inv(np.matmul(B.T,B)),B.T)
proyection_matrix = np.matmul(B,coord_matrix)
proyection_x = np.matmul(proyection_matrix,x)

print("proyection of x into U")
print(proyection_x)

proyection of x into U
[[10.]
 [ 4.]
 [-2.]]
