Exercises about solving linear equations, part of week 3 of course: https://www.coursera.org/learn/linear-algebra-machine-learning

In [31]:
import numpy as np

You go to the shops on Monday and buy 1 apple, 1 banana, and 1 carrot; the whole transaction totals €15. On Tuesday you buy 3 apples, 2 bananas, 1 carrot, all for €28. Then on Wednesday 2 apples, 1 banana, 2 carrots, for €23.

Construct a matrix and vector for this linear algebra system. That is, for

$A[[a],[b],[c]]=[[sMon],[sTue],[sWed]]$
Where aa, bb, cc, are the prices of apples, bananas, and carrots. And each ss is the total for that day.

Fill in the components of AA and s.

In [22]:
# Replace A and s with the correct values below:
A = [[1, 1, 1],
     [3, 2, 1],
     [2, 1, 2]]

s = [[15], 
     [28], 
     [23]]

convert the system to echelon form. I.e.,




In [12]:
A_augmented = np.hstack((A,s))
A1 = A_augmented[0]
A2 = A_augmented[1]
A3 = A_augmented[2]
print(A_augmented)

[[ 1  1  1 15]
 [ 3  2  1 28]
 [ 2  1  2 23]]


In [13]:
A1,A3 = A3,A1

print(A1)
print(A2)
print(A3)

[ 2  1  2 23]
[ 3  2  1 28]
[ 1  1  1 15]


In [14]:
A3 = A3 - A2/2 

print(A1)
print(A2)
print(A3)

[ 2  1  2 23]
[ 3  2  1 28]
[-0.5  0.   0.5  1. ]


In [15]:
A2 = A2 + 6*A3

print(A1)
print(A2)
print(A3)

[ 2  1  2 23]
[ 0.  2.  4. 34.]
[-0.5  0.   0.5  1. ]


In [16]:
A3 = A1 + 4*A3

print(A1)
print(A2)
print(A3)

[ 2  1  2 23]
[ 0.  2.  4. 34.]
[ 0.  1.  4. 27.]


In [17]:
A3 = A2 - 2*A3

print(A1)
print(A2)
print(A3)

[ 2  1  2 23]
[ 0.  2.  4. 34.]
[  0.   0.  -4. -20.]


In [18]:
A3 = A3*(-1/4)

print(A1)
print(A2)
print(A3)

[ 2  1  2 23]
[ 0.  2.  4. 34.]
[-0. -0.  1.  5.]


In [19]:
A2 = A2/2

print(A1)
print(A2)
print(A3)

[ 2  1  2 23]
[ 0.  1.  2. 17.]
[-0. -0.  1.  5.]


In [20]:
A1 = A1/2

print(A1)
print(A2)
print(A3)

[ 1.   0.5  1.  11.5]
[ 0.  1.  2. 17.]
[-0. -0.  1.  5.]


In [23]:
c = A3[3]
b = (A2[3]  - c*A2[2])/A2[1]
a = (A1[3]  - c*A1[2] - b*A1[1])/A1[0]

print(a,b,c)

3.0 7.0 5.0


If every week, you go to the shops and buy the same amount of apples, bananas, and oranges on Monday, Tuesday, and Wednesday; and every week you get a new list of daily totals - then you should solve the system in general.

That is, find the inverse of the matrix you used in Question 1.

In [26]:
A_inv = np.round(np.linalg.inv(A),2)

print(A_inv)

[[-1.5  0.5  0.5]
 [ 2.   0.  -1. ]
 [ 0.5 -0.5  0.5]]


In general, one shouldn't calculate the inverse of a matrix unless absolutely necessary. It is more computationally efficient to solve the linear algebra system if that is all you need.

Use this code block to solve the following linear system with numpy. Ar=s,

$[[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]]
     [[a],[b],[c]] = [[9],[7],[2]]
$


In [27]:
A = [[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]]

s = [9, 7, 2]

In [29]:
r = np.round(np.linalg.solve(A,s),2)

print(r)

[ 3.  -0.5 -0. ]
